XLite\Model\Config:
  - name: stripe_sep_1
    category: Iidev\Klaviyo
    type: separator
    orderby: 1000
    translations:
      - code: en
        option_name: "Account settings"
  - name: public_key
    category: Iidev\Klaviyo
    type: text
    orderby: 1100
    translations:
      - code: en
        option_name: "Public key"
  - name: secret_key
    category: Iidev\Klaviyo
    type: text
    orderby: 1200
    translations:
      - code: en
        option_name: "Secret key"
  - name: stripe_sep_2
    category: Iidev\Klaviyo
    type: separator
    orderby: 1300
    translations:
      - code: en
        option_name: "Content settings"
  - name: initial_list
    category: Iidev\Klaviyo
    type: text
    orderby: 1400
    translations:
      - code: en
        option_name: "Initial audience list"
  - name: footer_form
    category: Iidev\Klaviyo
    type: text
    orderby: 1500
    translations:
      - code: en
        option_name: "Footer form"
  - name: business_categories
    category: Iidev\Klaviyo
    type: text
    orderby: 1600
    translations:
      - code: en
        option_name: "Business categories"
